### PR TITLE
Improve exception message wording

### PR DESCRIPTION
**Pull request by filbertkm**

### CODE REVIEW

**Comment by filbertkm** [comment]
we are looking at the data values in the code, not "property type"

**Comment by thiemowmde** [comment]
The data value is `EntityIdValue`, which corresponds to the value type "wikibase-entityid" and is checked above. The line we are talking about here is about the property type (a.k.a. "data type").

This is similar to checking if a `StringValue` matches a URL pattern. This check looks at the string that is stored in a `StringValue`. What it contains depends on the property type being `url` or something else.

**Comment by filbertkm** [comment]
data types mean to have more specific constraints on the value in a property value snak and we are examining the value here. (which should match the property's data type / constraints)

I have tried rewording to explain the error in more detail and more clearly

**Comment by thiemowmde** [comment]
I really do not like the word "data type" because is so badly ambiguous, but whatever. This is just a safeguard that should never be seen.

**Comment by filbertkm** [comment]
if we want to move away from 'data type', i think we should make that change more broadly across the code base to keep consistency (and have a task for that)

**Comment by thiemowmde** [comment]
I just talked about exactly this somewhere else (can't find it right now). Basically, I have to disagree. There is not really much value in going through all the code and renaming variables for no other reason than "consistency". On the other hand, not doing so does not mean we are disallowed to name variables `$propertyType` when it makes sense. The `….datatypes.php` files already use `PT` for a long time, for example. For me, it feels more like being consistent when we continue to slowly move to "property type", or more specifically "property data type" if you like.

**Pull request merged**
