### PR TITLE
Update Wikibase CodeSniffer rule set to 0.2.0

### PR DESCRIPTION
**Pull request by thiemowmde**
This patch also:
* Removes meaningless return true from hooks. This is the default and
  does not do anything.
* Adds a namespace to the only class that was not in a namespace.

### CODE REVIEW

**Comment by Ladsgroup** [comment]
This is migrated to gerrit, right?

**Comment by JeroenDeDauw** [comment]
Looks like it. Just wanted to add `[READ-ONLY]` to the repo description and was confused for a minute by not seeing any edit button until I realized this is under a different GH org on which I don't have rights.

**Comment by manicki** [comment]
I believe @tobijat could add the READ-ONLY thing (I don't have rights either).

**Comment by thiemowmde** [comment]
Re-uploaded as https://gerrit.wikimedia.org/r/384493.

**Pull request closed without merging**
