### PR TITLE
Fix all jslint errors

### PR DESCRIPTION
**Pull request by mdew192837**
This fixes all jslint errors. However, I have decided to go with the multiline option in 35-37 while a single line option in the tertiary operators for readability. Let me know if something needs changing. @addshore

### CODE REVIEW

**Comment by thiemowmde** [comment]
Sorry to say that, but I would not have merged this. Almost nothing touched in this patch was an "error". Tell me: how is the fact that overly long, hard to read lines are split an "error"? Which weird JSLint setting reports this as an "error"? Why not disable this instead?

**Comment by mdew192837** [comment]
@thiemowmde 
This was for a GCI task. Phabricator task is here. https://phabricator.wikimedia.org/T96149
I was just saying I used a different convention for code readability. Let me know what you think.

**Comment by thiemowmde** [comment]
What "other" coding style was used here and why? Our coding conventions are described here: https://www.mediawiki.org/wiki/Wikibase/Coding_conventions. I can see at least two violations in this change:
* Lines should not be longer than 100 characters.
* Multi line `if`s should look like this:
````js
if ( condition
    && condition
    && condition
) {
````
Furthermore, we don't use JSLint but JSCS and JSHint, see https://phabricator.wikimedia.org/diffusion/EWBA/.

**Comment by mdew192837** [comment]
The if condiition you described gives jshint an error.
That is,
if ( foo
&& bar
&7 bar2 )
I used JSHint as well to test this. http://jshint.com/ Also, the tertiary operators throw an error as well if you split them up. I could not figure out a way to fix that on multilines. The syntax
foo
? foo2
: bar
Throws an error.
@thiemowmde Let me know how I can fix it.

**Comment by thiemowmde** [comment]
I dunno. Just revert this unnecessary change? Again, why was this done? What coding style was used here? How is the fact that overly long, unreadable lines are split an "error"? What made you think this needs "fixing"?

**Comment by manicki** [comment]
I believe what would be valuable is to add jscs and/or jshint (or maybe go for the future and use eslint) rule files to this repo. That way we would be able to ensure new code is also sticking to the code style, and the code style would then be explicitly visible.

Fixing the existing code is very helpful too (thanks @mdew192837) but I agree with @thiemowmde that we could go even further and specify the code style etc explicitly.

Oh, there is already https://github.com/Wikidata-lib/PropertySuggester/pull/156 related to this.

**Comment by addshore** [comment]
+1 to 
> I believe what would be valuable is to add jscs and/or jshint (or maybe go for the future and use eslint) rule files to this repo.

I think when agreeing to add this to GCI (in the state that it was in) this fact was overlooked.

**Comment by thiemowmde** [comment]
Please see #185. It is a much simpler alternative to #156.

I should explain that I strongly disagree with the idea to use the output of hinters and linters as "errors" that need "fixing". Preferring a certain code style over an other is not an "error". It can't be. The code runs. It's readable. Blindly following a set of arbitrary rules will lead to code that's *worse*, as this patch shows.

**Comment by mdew192837** [comment]
@addshore,
Do you want me to claim it on GCI and submit so I can get credit, or are you going to just remove it as a task altogether? (I abandoned it per comments and so I could do other tasks)
Thanks!

**Comment by addshore** [comment]
@mdew192837 if you reclaim it I can mark it as done!

**Comment by mdew192837** [comment]
@addshore Submitted. Thanks!
Sorry for the confusion everybody. At least we know how to process in the future. :)

**Pull request merged**
