### PR TITLE
Enable all property suggestions

### PR DESCRIPTION
**Pull request by GlorianY**
Include all property suggestions when the corresponding parameter (all_suggestions) is enabled. See https://phabricator.wikimedia.org/T164994

### CODE REVIEW

**Comment by Ladsgroup** [comment]
We are moving this project to gerrit, please make a patch against gerrit and also please follow coding styles.

**Comment by manicki** [comment]
@GlorianY: see https://gerrit.wikimedia.org/r/#/admin/projects/mediawiki/extensions/PropertySuggester

**Comment by manicki** [comment]
And if you need any help with make a patch on gerrit, please ping someone of WMDE at IRC (or any other way, mentioning IRC as I know you're familiar with it).

**Comment by GlorianY** [comment]
Thanks for the review @Ladsgroup, I have changed my patch in accordance with the coding convention.

Thanks @manicki, I have submitted the patch on Geritt (https://gerrit.wikimedia.org/r/#/c/356043/).

**Pull request closed without merging**
