### PR TITLE
Release notes240

### PR DESCRIPTION
**Pull request by addshore**

### CODE REVIEW

**Comment by thiemowmde** [comment]
How is that a "new feature"? A 2.3.2 should be enough.

**Comment by addshore** [comment]
I guess this basically comes down to weather or not we would count the SuggestionGenerator class as public or private.
Of course I am assuming public as it does not explicitly say private...

Really in this case this should be 3.0.0 and this is incompatible with the previous version..
But the versionning of this extension is already messed up anyway due to not being able to specify a version of wikibase to depend on

blergh, its a pile of version fun

**Comment by thiemowmde** [comment]
I do not understand what you are talking about. SuggestionGenerator is there since 1.x and has not changed. What I see in https://github.com/Wikidata-lib/PropertySuggester/compare/2.3.1...master suggests a 2.3.2.

**Comment by JeroenDeDauw** [comment]
@addshore don't forget to distinguish between libraries and applications. For the later, the more important types of breaks tend to be the ones visible to the users.

**Comment by filbertkm** [comment]
imho, I think introducing a dependency on data model services is enough to warrant bumping to 2.4.0 here.

(and we need to tag to unbreak stuff)

**Pull request merged**
