### PR TITLE
Require PHP 5.5

### PR DESCRIPTION
**Pull request by JeroenDeDauw**
Matching changes in #154

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
I just noticed that apparently the goal of #154 was not to remove PHP <5.5 support, but rather to ignore the test failures. Personally I think one should always test against the lowest version allowed by `composer.json` and never have this go out of sync. However beware that the merge of this might not be desired yet if 5.3 still needs to be supported.

**Comment by addshore** [comment]
> However beware that the merge of this might not be desired yet if 5.3 still needs to be supported.

Yeh, doesn't master of this get pulled straight into the build?
Which would mean the build is now broken?

**Comment by filbertkm** [comment]
I trust Marius in reviewing this.

we use a tagged version of property suggester in the build.

**Comment by addshore** [comment]
Then this should be fine :)

**Pull request merged**
