### PR TITLE
add initial suggestions from configuration

### PR DESCRIPTION
**Pull request by xchrdw**
fixes https://phabricator.wikimedia.org/T92748

### CODE REVIEW

**Comment by filbertkm** [comment]
rebased https://github.com/Wikidata-lib/PropertySuggester/tree/initialSuggestionsRebased

I'm not sure how to rebase within this pull request, without doing a force push?

**Comment by filbertkm** [comment]
doesn't yet address Thiemo's comments.

**Comment by tobijat** [comment]
@aude do I understand correctly that this will resolve https://phabricator.wikimedia.org/T92748?

**Comment by filbertkm** [comment]
@tobijat yes this will.  it's just a question now how to get this in (with my rebase?) and then address Thiemo's concerns (who wants to do that).

**Comment by thiemowmde** [comment]
What I wrote is just a suggestion. Property suggester is build on numeric ids. I would like to avoid them but this is no reason to block this patch. Feel free to merge.

**Comment by mariushoch** [comment]
Superseded by #120

**Pull request closed without merging**
