### PR TITLE
Convert PropertySuggester to extension registration

### PR DESCRIPTION
**Pull request by reedy**
[Bug: T124055](https://phabricator.wikimedia.org/T124055)

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
Bunch of tests failing with

    array_flip(): Can only flip STRING and INTEGER values!

**Comment by reedy** [comment]
>I wonder if the removed require… '/vendor/autoload.php' line might still be relevant for something?

The extension.json equivalent is as below (which is included)
```lang=json
"load_composer_autoloader": true,
```

**Comment by reedy** [comment]
The failing test lines seem to be where the variables are used.

I guess a var_dump of the usages one up in the stack would be enough to work out what it's ending up with

The obvious one would be {} vs [], but the code is clearly using []

**Comment by reedy** [comment]
OH. Duh. It's beause manifest_version 1 and using value in the config.

Do you want manifest_version 1 or 2?

You're not using any version 2 config... So we might aswell fully revert to 1 as we're not gonna lose any functionality, and it keeps some further back compat

**Comment by reedy** [comment]
Let's see what the tests do this time :)

**Comment by thiemowmde** [comment]
> The extension.json equivalent is […] load_composer_autoloader

Good to know this. thanks!

> Do you want manifest_version 1 or 2?

Personally, I don't care much, as long as these two formats can easily be converted to each other.

> the code is clearly using []

I would like to understand to which code you are referring to. Unfortunately you did not uploaded a second commit, so I can't see the difference.

**Comment by reedy** [comment]
manifest_version 1 https://github.com/wikimedia/mediawiki/blob/master/docs/extension.schema.v1.json#L666-L693
```
	"config": {
		"MyConfigArray": [
			1,
			2
		]
	}
```

manifest_version 2 https://github.com/wikimedia/mediawiki/blob/master/docs/extension.schema.v2.json#L681-L723
```
	"config": {
		"MyConfigArray": {
			"value": [
				1,
				2
			]
		}
	}
```


Basically, I converted it using the maintenance script, which did it to manifest_version 2 with the value properties. I then manually swapped it to manifest_verison 1, but forgot to remove out the value properties

**Pull request merged**
